var DOC_DATA = {
    "meta": {
        "docNumber": "BRD-OOO-260707.Instr",
        "version": "v2.1:03",
        "date": "2026-08-15",
        "status": "现行有效",
        "pageTitle": "使用说明",
        "pageBrand": "OOOInterface",
        "pageTitleMain": "使用说明",
        "pageSubtitle": "OOOInterface 使用说明",
        "footerLeft": "OOOInterface · ByRUDAN",
        "footerRight": ""
    },
    "sections": [
        {
            "id": 0,
            "label": "基本介绍",
            "title": "OOOInterface 基本介绍",
            "content":
                [
                    "<p>在当前的数字生态系统中，浏览器新标签页（New Tab Page, NTP）作为用户高频访问的入口节点，其交互效率与视觉体验直接决定了用户的数字工作流效能。OOOInterface 是一款基于 Chromium 内核架构深度定制的 Chrome 扩展插件，旨在从根本上重构浏览器新标签页的默认交互范式。通过精准拦截并替换浏览器原生的新标签页渲染逻辑，OOOInterface 为用户提供了一个高度可定制、视觉层级清晰的自定义首页界面，从而实现了对传统浏览器默认首页的功能替代与体验升级。</p>",
                    "<p>在底层开发哲学上，OOOInterface 始终遵循“用户体验优先（UX-First）”的核心原则。在交互设计层面，产品致力于构建超轻量级的运行时环境，通过极致的代码优化与资源调度策略，确保插件在注入新标签页时保持毫秒级的响应速度，杜绝因 DOM 元素冗余或脚本阻塞导致的页面卡顿现象，从而保障用户浏览体验的流畅性与连贯性。与此同时，在视觉呈现层面，OOOInterface 引入了现代化的极简主义美学设计系统。界面布局严格遵循视觉平衡与留白原则，摒弃了传统浏览器首页常见的信息过载与视觉噪点，为用户营造出沉浸式的视觉交互空间。这种“超美观”的设计不仅提升了界面的审美层级，更在认知心理学层面有效降低了用户的视觉疲劳度与操作认知负荷。</p>",
                    "<p>为了确保产品能够持续契合用户的核心诉求，OOOInterface 建立了严密且高效的用户反馈闭环系统。产品团队摒弃了单向度的功能输出模式，转而采用以真实用户声音为导向的敏捷开发策略。通过建立多维度的用户意见收集渠道，团队能够对用户在真实使用场景下的痛点与需求进行量化分析与定性评估。这种对用户体验的持续倾听与深度洞察，直接驱动了产品核心功能的持续优化与迭代，确保了每一次版本更新都能精准解决用户的实际问题。</p>",
                    "<p>在商业模式与生态建设层面，OOOInterface 确立了“永久开源、永久免费”的长期战略承诺。通过将核心源代码完全向社区开放，产品不仅赋予了技术社区对代码安全性与隐私合规性的完全审计权，更构建了一个透明、可信的开源协作生态。这一举措彻底消除了用户对商业插件潜在的数据隐私风险与付费墙限制的顾虑，彰显了产品致力于为用户提供纯粹、无干扰的浏览器首页体验的长期愿景与社会责任。</p>"
                ]
        },
        {
            "id": 1,
            "label": "历史版本",
            "title": "OOOInterface 历史版本",
            "content": [
                "<div class='version-card'><div class='version-head'><span class='ver-num'>1.0:01</span><h3 class='version-title'>首个版本</h3></div><p>以 Google.com 外观为原型，Google Logo 居中，搜索框和搜索引擎切换按钮方便用户搜索。界面简洁，操作简单。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>1.1:02</span><h3 class='version-title'>版本迭代</h3></div><p>完善界面整体清晰度，优化 Google Logo 清晰度。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>1.2:03</span><h3 class='version-title'>版本迭代</h3></div><p>完善界面整体清晰度，优化 Google Logo 清晰度。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>1.3:04</span><h3 class='version-title'>版本迭代</h3></div><p>完善界面整体清晰度，优化 Google Logo 清晰度。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>1.4:05</span><h3 class='version-title'>版本迭代</h3></div><p>完善界面整体清晰度，优化 Google Logo 清晰度。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>2.0:06</span><h3 class='version-title'>界面优化</h3></div><p>完善界面整体清晰度，解决 Google Logo 模糊问题，优化细节，加入铭牌 \"Designed By RUDAN\"</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>2.1:07</span><h3 class='version-title'>版本迭代</h3></div><p>试图解决加载为插件后切换引擎按钮无法使用问题，同时完善界面整体清晰度。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>2.2:08</span><h3 class='version-title'>版本迭代</h3></div><p>试图解决加载为插件后切换引擎按钮无法使用问题，同时完善界面整体清晰度。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>2.3:09</span><h3 class='version-title'>版本迭代</h3></div><p>试图解决加载为插件后切换引擎按钮无法使用问题，同时完善界面整体清晰度。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>2.4:10</span><h3 class='version-title'>版本迭代</h3></div><p>试图解决加载为插件后切换引擎按钮无法使用问题，同时完善界面整体清晰度。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>2.5:11</span><h3 class='version-title'>版本迭代</h3></div><p>试图解决加载为插件后切换引擎按钮无法使用问题，同时完善界面整体清晰度。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>2.6:12</span><h3 class='version-title'>版本迭代</h3></div><p>试图解决加载为插件后切换引擎按钮无法使用问题，同时完善界面整体清晰度。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>2.7:13</span><h3 class='version-title'>版本迭代</h3></div><p>试图解决加载为插件后切换引擎按钮无法使用问题，同时完善界面整体清晰度。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>2.8:14</span><h3 class='version-title'>版本迭代</h3></div><p>试图解决加载为插件后切换引擎按钮无法使用问题，同时完善界面整体清晰度。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>2.9:15</span><h3 class='version-title'>版本迭代</h3></div><p>试图解决加载为插件后切换引擎按钮无法使用问题，同时完善界面整体清晰度。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>3.0:16</span><h3 class='version-title'>功能扩展</h3></div><p>修复了前 n 多个版本 Bing 无法使用的 Bug。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>3.1:17</span><h3 class='version-title'>功能扩展</h3></div><p>加入全新字体 Josefin Sans，优化下滑界面。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>3.2:18</span><h3 class='version-title'>功能扩展</h3></div><p>加入全新壁纸，下滑预览。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>3.3:19</span><h3 class='version-title'>功能扩展</h3></div><p>针对不同屏幕比例的壁纸完成适配，搜索框文字简化，底部名牌更改为 \"OOO Interface 3.3\"。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>3.4:20</span><h3 class='version-title'>功能扩展</h3></div><p>加入全新字体\"ABC Ginto Variable\",优化稳定性。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>3.5:21</span><h3 class='version-title'>功能扩展</h3></div><p>支持在\"Setting\"中自行更换字体，搜索框增加灰框提升可读性，搜索引擎按钮增加切换高亮。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>4.0:22</span><h3 class='version-title'>UI更新</h3></div><p>整体UI更加圆润。搜索框位置下调。新增设置按钮自动隐藏，切换字体设置将全局可用。下滑可以调整搜索引擎。</p></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.0:23</span><h3 class='version-title'>功能全面升级</h3></div><h4 class='version-subtitle'>更新了什么？</h4><ul><li>UI加入光照效果，提升可读性</li><li>支持多种图标(Google/Microsoft/Apple/HUAWEI/自定义图片/自定义文字)</li><li>支持自定义字体和背景</li><li>支持新增/删除快速访问链接</li><li>更改设置入口：右键底部铭牌或双击界面中部</li><li>设置页面支持鼠标上滑打开</li><li>底部铭牌样式变化：显示文字\"OOO Interface\"，单击后显示具体版本号</li></ul><h4 class='version-subtitle'>什么是更多？</h4><ul><li>优化设置页面显示效果</li><li>优化不同logo时搜索引擎切换按钮显示效果</li><li>修复了一些已知问题</li></ul></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.1:24</span><h3 class='version-title'>修复显示问题，新增实用功能</h3></div><h4 class='version-subtitle'>更新了什么？</h4><ul><li>新增字体大小和粗细调节</li><li>新增右键Google网页直达功能</li><li>新增搜索历史功能</li><li>新增全新右键菜单</li><li>全新横屏设置页面</li><li>新增反馈入口和全新的关于页面</li></ul><h4 class='version-subtitle'>什么是更多？</h4><ul><li>设置页面部分显示效果</li><li>内存占用和流畅性</li><li>亮色模式下显示效果修复</li><li>修复一些已知Bug</li></ul></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.1.1:24</span><h3 class='version-title'>紧急修复严重漏洞</h3></div><h4 class='version-subtitle'>修复内容</h4><ul><li>修复设置页面部分显示效果。</li><li>修复内存占用和流畅性问题。</li><li>修复了关于页面网址错误。</li><li>修复了一些已知Bug。</li></ul></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.1.2:24</span><h3 class='version-title'>修复漏洞</h3></div><h4 class='version-subtitle'>修复内容</h4><ul><li>加入全新云图标。</li><li>引入全新反馈系统。</li><li>修复内存占用和流畅性问题。</li><li>修复了一些已知Bug。</li></ul></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.1.3:24</span><h3 class='version-title'>版本更新</h3></div><h4 class='version-subtitle'>新增内容</h4><ul><li>新版本地图标。</li></ul><h4 class='version-subtitle'>修复内容</h4><ul><li>修复内存占用和流畅性问题。</li><li>修复了一些已知Bug。</li></ul></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.2:25</span><h3 class='version-title'>版本更新</h3></div><h4 class='version-subtitle'>界面重构</h4><ul><li>设置页面：统一按钮圆角规范，移除冗余阴影，显著提升视觉简洁性与界面统一性</li><li>设置页面：优化多分辨率屏幕下右侧选项框的自适应显示效果</li><li>关于页面：采用全新卡片式布局设计，采用全新历史版本API接口</li></ul><h4 class='version-subtitle'>视觉效果增强</h4><ul><li>新增右键菜单渐入动画效果</li><li>新增应用按钮退出设置页面的动态过渡效果</li><li>新增设置页面、搜索框、搜索引擎切换按钮、快速访问链接及搜索历史框的毛玻璃模糊效果</li><li>新增动态背景粒子系统</li><li>优化壁纸模式进入动画流程</li><li>改进壁纸常显示模式的呈现效果</li></ul><h4 class='version-subtitle'>增强显示视效</h4><ul><li>新增全新光照效果</li><li>新增关于页面丝滑动画</li></ul><h4 class='version-subtitle'>新增功能</h4><ul><li>快速粘贴功能：支持在搜索框内右键快速插入剪贴板内容</li><li>搜索框一键清除：支持一键清除搜索框内容</li><li>壁纸显示：新增壁纸缩放功能，新增必应每日壁纸</li><li>提示框模块：可通过网络获取版本更新提示信息</li><li>用户反馈页面</li></ul><h4 class='version-subtitle'>开发者模式优化</h4><ul><li>加入全新代理配置入口</li><li>四项数据内容全面支持滑块拖动与数值输入双重调整方式</li><li>调整部分参数上限设置</li><li>字体粗细调整新增自动四舍五入功能</li><li>优化开发者模式在亮色主题下的显示效果</li></ul><h4 class='version-subtitle'>问题修复</h4><ul><li>修复右键菜单\"设置\"选项无法正常打开的问题</li><li>修复多页面间版本号显示不一致的问题</li><li>优化自定义Logo体验</li><li>优化自定义表单，提供删除按钮</li></ul></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.2:26</span><h3 class='version-title'>版本更新</h3></div><h4 class='version-subtitle'>界面优化</h4><ul><li>优化壁纸模式搜索框显示效果</li><li>优化底部铭牌动画</li><li>优化高级视觉效果壁纸模式搜索框、右键菜单模糊效果设置页面</li></ul><h4 class='version-subtitle'>导航改进</h4><ul><li>头部新增\"关于\"和\"反馈\"按钮，与关闭按钮并排，用于代替原有底部按钮（原有按钮即将删除）</li><li>反馈图标从 feedback 改为 bug_report</li></ul><h4 class='version-subtitle'>细节优化</h4><ul><li>优化组间间距</li><li>优化部分页面模糊效果右键菜单</li></ul><h4 class='version-subtitle'>新功能</h4><ul><li>新增\"极简\"右键菜单样式选项</li><li>隐藏非开发者模式下\"反馈\"按钮重构底层代码</li></ul><h4 class='version-subtitle'>代码重构</h4><ul><li>欢迎页文字内容抽离到 update.js ，HTML改为动态渲染</li><li>大幅精简CSS样式代码</li><li>新增 content_security_policy 配置</li></ul></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.2:27</span><h3 class='version-title'>版本更新</h3></div><h4 class='version-subtitle'>主页面</h4><ul><li>推出全新新一代快速访问链接</li><li>推出全新隐藏弹窗功能</li><li>推出全新状态栏</li><li>加入搜索框自动追焦</li><li>窄屏适配</li></ul><h4 class='version-subtitle'>快速访问链接</h4><ul><li>新增一键导入书签功能</li><li>新增一键清空快速访问链接功能</li></ul><h4 class='version-subtitle'>设置页面</h4><ul><li>新增自定义右键菜单</li><li>应用设置不再强制刷新整个页面</li><li>设置页面应用逻辑重构</li></ul><h4 class='version-subtitle'>设置页面显示效果优化</h4><ul><li>显示效果优化</li><li>搜索框效果优化</li><li>窄屏显示效果优化</li><li>快速访问链接拖动优化</li><li>快速访问链接面板优化</li><li>页面弹窗显示效果优化</li><li>设置页面进入动画优化</li></ul></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.1.4:24.4</span><h3 class='version-title'>提供最新补丁</h3></div><h4 class='version-subtitle'>更新内容</h4><ul><li>为更棒的下一代OOOInterface预备好。</li></ul><h4 class='version-subtitle'>修复内容</h4><ul><li>修复了一些已知Bug。</li></ul></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.2.1:25.1</span><h3 class='version-title'>提供最新补丁</h3></div><h4 class='version-subtitle'>更新内容</h4><ul><li>为更棒的下一代OOOInterface预备好。</li></ul><h4 class='version-subtitle'>修复内容</h4><ul><li>修复了一些已知Bug。</li></ul></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.2:27.1</span><h3 class='version-title'>提供最新补丁</h3></div><h4 class='version-subtitle'>更新内容</h4><ul><li>为更棒的下一代OOOInterface预备好。</li></ul><h4 class='version-subtitle'>修复内容</h4><ul><li>修复了一些已知Bug。</li></ul></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.2.1:28</span><h3 class='version-title'>版本更新</h3></div><h4 class='version-subtitle'>壁纸设置</h4><ul><li>推出一键导入系列壁纸，爸爸妈妈再也不怕我大量壁纸同时导入累死了</li><li>新增大量壁纸一键清除，爸爸妈妈再也不怕我手删除一堆张壁纸累死了</li><li>优化壁纸导入速度</li><li>优化清除壁纸效果</li></ul><h4 class='version-subtitle'>主题色设置</h4><ul><li>新增主题色自定义功能，爸爸妈妈再也不怕我看破绿色视觉疲劳了</li><li>优化页面配色显示效果</li></ul><h4 class='version-subtitle'>快捷键操作</h4><ul><li>新增快捷键操作，爸爸妈妈再也不怕我各种操作繁杂难操作崩溃了</li><li>优化 ESC 关闭窗口体验</li></ul></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.2.4:29</span><h3 class='version-title'>版本更新</h3></div><h4 class='version-subtitle'>新增功能</h4><ul><li>新增主题功能</li><li>新增XBOX手柄控制</li><li>新增已添加快速访问链接编辑功能</li><li>重构颜色自定义逻辑，新增自定义按钮，支持无限数量自定义配色</li><li>新增搜索引擎锁定功能</li><li>新增主题菜单前往主题商店入口</li></ul><h4 class='version-subtitle'>XBOX手柄控制</h4><ul><li>LT：删除</li><li>LB：呼出快捷轮盘</li><li>RT：粘贴</li><li>RB：复制</li><li>左摇杆：空鼠</li><li>四向按钮：上下左右选择器</li><li>右摇杆：上下左右选择器</li><li>A：ESC/返回</li><li>B：确认/左键</li><li>X：菜单键/右键</li><li>Y：回车键/确认</li><li>LS/RS：允许用户自定义</li><li>A/B：允许对应功能反转</li></ul><h4 class='version-subtitle'>显示优化</h4><ul><li>优化设置页顶部边距，平衡视觉效果</li><li>降低快速访问链接面板层级，窄屏设置能够正常使用</li><li>统一设置页右面板按钮样式，优化按钮圆角</li><li>优化快速访问链接调整顺序体验，虚线改为实线</li><li>优化右面板文件拖入体验，虚线改为实线</li><li>关于页面 OOOInterface 图标大小优化</li><li>关于页面 OOOInterface 官网描述文本修改</li></ul></div>",
                "<div class='version-card'><div class='version-head'><span class='ver-num'>5.3:30</span><h3 class='version-title'>版本更新</h3></div><h4 class='version-subtitle'>壁纸功能</h4><h4 class='version-subtitle'>优化</h4><ul><li>优化壁纸模式搜索框显示效果</li><li>优化壁纸导入速度</li><li>优化清除壁纸效果</li></ul><h4 class='version-subtitle'>新增</h4><ul><li>推出一键导入系列壁纸</li><li>新增大量壁纸一键清除</li></ul><h4 class='version-subtitle'>界面交互</h4><h4 class='version-subtitle'>优化</h4><ul><li>优化底部铭牌动画</li><li>优化搜索框效果</li><li>优化页面弹窗显示效果</li><li>优化设置页面进入动画</li><li>优化快速访问链接拖动体验</li><li>优化快速访问链接调整顺序体验，虚线改为实线</li><li>优化右面板文件拖入体验，虚线改为实线</li><li>优化 ESC 关闭窗口体验</li><li>优化设置页顶部边距，平衡视觉效果</li><li>优化组间间距</li></ul><h4 class='version-subtitle'>新增</h4><ul><li>推出全新新一代快速访问链接</li><li>加入搜索框自动追焦</li><li>新增一键导入书签功能</li><li>新增一键清空快速访问链接功能</li><li>新增已添加快速访问链接编辑功能</li></ul><h4 class='version-subtitle'>视觉效果</h4><h4 class='version-subtitle'>优化</h4><ul><li>优化高级视觉效果壁纸模式搜索框、右键菜单模糊效果设置页面</li><li>优化部分页面模糊效果右键菜单</li><li>优化页面配色显示效果</li><li>窄屏显示效果优化</li><li>降低快速访问链接面板层级，窄屏设置能够正常使用</li><li>统一设置页右面板按钮样式，优化按钮圆角</li><li>新增\"极简\"右键菜单样式选项</li></ul><h4 class='version-subtitle'>新增</h4><ul><li>推出全新状态栏</li><li>窄屏适配</li><li>新增主题功能</li><li>新增主题色自定义功能</li></ul><h4 class='version-subtitle'>代码质量</h4><h4 class='version-subtitle'>优化</h4><ul><li>欢迎页文字内容抽离到 update.js，HTML改为动态渲染</li><li>大幅精简CSS样式代码</li><li>显示效果优化</li><li>窄屏显示效果优化</li></ul><h4 class='version-subtitle'>重构</h4><ul><li>隐藏非开发者模式下\"反馈\"按钮重构底层代码</li><li>应用设置不再强制刷新整个页面</li><li>设置页面应用逻辑重构</li><li>重构颜色自定义逻辑，新增自定义按钮，支持无限数量自定义配色</li></ul><h4 class='version-subtitle'>功能扩展</h4><h4 class='version-subtitle'>新增</h4><ul><li>新增自定义右键菜单</li><li>新增搜索引擎锁定功能</li><li>新增主题菜单前往主题商店入口</li><li>新增XBOX手柄控制功能</li></ul><h4 class='version-subtitle'>安全配置</h4><h4 class='version-subtitle'>新增</h4><ul><li>新增 content_security_policy 配置</li></ul><h4 class='version-subtitle'>其他优化</h4><ul><li>关于页面 OOOInterface 图标大小优化</li><li>关于页面 OOOInterface 官网描述文本修改</li><li>新增隐藏弹窗功能</li></ul></div>"
            ]
        },
        {
            "id": 2,
            "label": "使用教程",
            "title": "OOOInterface 使用教程",
            "content": [
                "<h2>OOOInterface 通用词汇</h2>",
                "<ul><li>主页面：OOOInterface 主页面，包括搜索框、搜索引擎切换按钮、搜索历史框、底部铭牌。</li><li>搜索框：屏幕中央处长条栏目，支持文本键入。</li><li>搜索引擎切换按钮：搜索框下方按钮。</li><li>搜索历史框：记录搜索历史，仅在有搜索记录时展开。</li><li>快速访问链接：添加至主页面的网页链接快捷按钮。</li><li>底部铭牌：屏幕底部铭牌，标有\"OOOInterface\"。</li><li>壁纸模式：仅保留搜索框、搜索引擎切换按钮，并显示壁纸的页面。</li><li>右键菜单：随动快捷栏。</li><li>设置页面：OOOInterface 设置页面，包括多项内容设定。</li><li>必应（Bing）每日壁纸：通过云端拉取 Microsoft Bing 提供的壁纸为 OOOInterface 带来多样化的壁纸体验。</li><li>高级视觉效果：为用户提供毛玻璃等更加精美的视觉体验（可能会增加性能消耗）。</li><li>壁纸常显示：在主页面仍然显示壁纸（推荐同时打开「壁纸缩放」）。</li><li>快速访问侧边栏：为快速访问链接提供全新侧面板样式。</li><li>开发者模式：为用户提供更多设置项（测试），可能不稳定。</li><li>关于页面：展示当前版本核心信息和历史版本信息。</li><li>反馈页面：OOOInterface 收集用户反馈的页面。</li></ul>",
                "<h2>安装 OOOInterface</h2>",
                "<ol><li>Chrome浏览器，进入chrome://extensions/。</li><li>开启右上角的\"开发者模式\"。</li><li>点击\"加载已解压的扩展程序\"。</li><li>选择本项目所在文件夹。</li><li>新建浏览器标签页。</li><li>进入欢迎页面。</li><li>点按空格进行下一步。</li><li>进入主页面。</li></ol>",
                "<h2>主页面使用</h2>",
                "<h3>搜索与导航</h3>",
                "<h4>搜索框操作</h4>",
                "<ul><li>默认情况下，打开页面后搜索框将自动获得焦点，用户可直接键入内容。</li><li>按 Enter 键执行搜索，搜索结果将跳转至当前搜索引擎的结果页面。</li><li>搜索框内有内容时，右侧将出现清除按钮，点击即可一键清空搜索内容。</li><li>在搜索框内右键可快速粘贴剪贴板内容。</li></ul>",
                "<h4>搜索引擎切换</h4>",
                "<p>搜索框下方提供 Google 与 Bing 两个搜索引擎切换按钮，点击即可切换当前使用的搜索引擎。在设置页面开启「引擎锁定」后，搜索引擎将被固定，切换按钮不可点击。</p>",
                "<h4>搜索历史</h4>",
                "<p>在搜索框内输入内容时，下方会自动弹出匹配的历史记录列表供快速选取；也可通过快捷键 Ctrl+H 手动展开或收起。右键菜单中的「搜索历史」选项可切换该功能的开与关。历史记录仅保存在本地，随时可在设置中关闭此功能。</p>",
                "<h4>状态栏</h4>",
                "<p>屏幕顶部显示当前日期与时间，双击状态栏本身可快速切换秒钟的显隐。需先在设置中启用。</p>",
                "<h4>壁纸模式</h4>",
                "<p>在主页面状态下，向下滚动鼠标滚轮即可进入壁纸模式——此时页面将仅保留搜索框、搜索引擎切换按钮及完整的壁纸背景，为用户提供沉浸式的搜索体验。向上滚动即可返回主页面。</p>",
                "<blockquote>注：若已在设置中开启「壁纸常显示」，壁纸将常驻于主页面，向下滚动仍可同时触发壁纸模式的沉浸式效果。</blockquote>",
                "<h3>右键菜单</h3>",
                "<p>在页面任意空白处右键单击即可唤出随动快捷栏（右键菜单）。菜单分为固定选项与勾选切换项两类：</p>",
                "<ul><li>固定选项（始终显示）：复制、粘贴、设置、刷新、关于、反馈。</li><li>勾选切换项：右键菜单中的功能切换项（如搜索历史、壁纸常显示等），默认显示部分项目，可在设置页面自定义最多三项的显示内容。</li></ul>",
                "<p>可在设置页面中进一步自定义菜单的显示样式与包含的项目。</p>",
                "<h3>快速访问链接</h3>",
                "<p>快速访问链接是主页面上的一排快捷按钮，可快速跳转至常用网站。</p>",
                "<ul><li>管理链接：在设置页面选择「管理链接」，即可对快速访问链接进行增删改查操作。</li><li>导入与导出：支持将快速访问链接导出为 JSON 文件备份，或导入外部 JSON 文件快速恢复链接列表（同名同址重复项将自动跳过）。</li></ul>",
                "<h2>设置</h2>",
                "<h3>基础操作</h3>",
                "<h4>设置页面</h4>",
                "<p>设置页面是个性化您的 OOOInterface 的重要窗口。在这里您可以自由定制您的 OOOInterface。</p>",
                "<ul><li>打开设置页面：您可以通过双击或右键单击底部铭牌，或在右键菜单中点击「设置」来打开。</li><li>完成和保存设置：完成设置后，点击「完成」保存更改。按下「ESC」或点击右上角关闭按钮可关闭设置页面。</li><li>返回上一个设置项：部分设置项会在右侧面板中展开，完成后可点击右上角返回按钮或按下「ESC」返回。</li><li>重置：单击重置按钮将清空所有设置项，请谨慎操作。</li></ul>",
                "<h3>外观设置</h3>",
                "<h4>主题设置</h4>",
                "<p>OOOInterface 为用户提供了多样化的主题，并提供了上传主题的入口和官方主题商店。</p>",
                "<p>若您需要上传自己的主题，点击「+」按钮，找到主题目录，选中主题文件，点击确认（不同操作系统使用体验可能略有不同）即可。您也可以通过拖拽将主题文件拖入。</p>",
                "<h4>字体设置</h4>",
                "<p>OOOInterface 为用户提供了丰富的免费字体，并提供了上传字体的入口。</p>",
                "<p>若您需要上传自己的字体，点击「+」按钮，找到字体目录，选中字体，点击确认（不同操作系统使用体验可能略有不同）即可。您也可以通过拖拽将字体文件拖入。</p>",
                "<h4>Logo 设置</h4>",
                "<p>OOOInterface 为用户提供了多样化的 Logo，并提供了自定义文字 Logo 和上传 Logo 的入口。</p>",
                "<p>若您需要上传自己的 Logo，点击「+」按钮，找到字体目录，选中图片文件，点击确认（不同操作系统使用体验可能略有不同）即可。您也可以通过拖拽将图片文件拖入。</p>",
                "<h4>自定义文字 Logo</h4>",
                "<p>在 Logo 设置下拉菜单中选择「自定义文字Logo」，即可展开文字输入框。在输入框中输入您想展示的文字后，点击右侧确定按钮即可完成设置。</p>",
                "<h4>配色方案</h4>",
                "<p>OOOInterface 为用户提供多种预设配色方案，涵盖经典与新兴风格：</p>",
                "<ul><li>林绿色、经典蓝、黑白色：经典三色系，适配不同使用场景。</li><li>天依蓝、活力红、典藏金、隔离色：新增风格系，提供更为丰富的视觉选择。</li></ul>",
                "<p>用户可在「选择配色」下拉菜单中直接选取，配色更改将即时生效。</p>",
                "<h4>壁纸设置</h4>",
                "<ul><li>壁纸来源：用户可根据需求选择壁纸来源，包括默认壁纸、必应每日壁纸（通过云端拉取 Microsoft Bing 提供的壁纸并保持每日更新）、URL链接（填入图片网络链接）以及本地图片（点击「+」按钮选择或直接拖拽）。在设置页面点击「必应每日壁纸」旁的信息图标可了解详细说明。</li><li>壁纸常显示：开启后，壁纸将在主页面常驻显示，不再需要滚动即可看到完整背景。建议同时开启「壁纸缩放」以获得更佳的视觉比例。</li><li>壁纸缩放：开启后，壁纸将按照屏幕比例进行缩放填充，避免出现黑边或裁切过多内容。此选项仅在「壁纸常显示」开启时可见。</li></ul>",
                "<h3>功能设置</h3>",
                "<h4>状态栏</h4>",
                "<ul><li>打开方式：在设置页面勾选「状态栏」开关即可启用。</li><li>显示秒钟：开启状态栏后，可进一步勾选「显示秒钟」以在状态栏中显示精确到秒的时间。</li></ul>",
                "<h4>高级视觉效果与增强显示</h4>",
                "<ul><li>高级视觉效果：开启后将启用毛玻璃等动态模糊效果，为界面增添层次感，但可能会增加部分性能消耗。</li><li>增强显示：开启后将展示全新的光照效果，进一步提升界面的视觉质感。该选项仅在「高级视觉效果」开启时可见。</li></ul>",
                "<blockquote>注：「高级视觉效果」和「增强显示」均为独立功能，用户可根据自身设备性能灵活组合使用。</blockquote>",
                "<h4>搜索历史</h4>",
                "<p>搜索历史功能会自动记录用户的搜索关键词，并保存在本地。</p>",
                "<ul><li>开启后，当用户在搜索框内输入内容时，下方将自动弹出匹配的历史记录列表。</li><li>用户可直接点击历史记录条目以快速执行搜索。</li><li>在设置页面可随时关闭此功能。</li></ul>",
                "<h4>右键菜单设置</h4>",
                "<p>右键菜单提供三种样式，可在设置页面「右键菜单样式」中切换：</p>",
                "<table><tr><td>样式</td><td>说明</td></tr><tr><td>------</td><td>------</td></tr><tr><td>默认</td><td>完整网格布局，显示全部图标与文字</td></tr><tr><td>紧凑</td><td>图标与文字并列，布局更节省空间</td></tr><tr><td>极简</td><td>仅显示图标，不显示文字，同时禁用自定义菜单项功能</td></tr></table>",
                "<p>勾选切换项的显示数量最多三项，可在设置页面「右键菜单样式」右侧面板中点击右上角的设置图标（自定义菜单项）进行增减。可选项目包括：搜索历史、壁纸常显示、高级视觉效果、引擎锁定、隐藏弹窗、禁止提示。</p>",
                "<h4>快速访问链接设置</h4>",
                "<ul><li>侧边栏样式：开启「快速访问侧边栏」后，快速访问链接将以侧面板形式展示于页面右侧，需从左侧边缘呼出。</li><li>显示图标：开启后，侧边栏中的链接按钮会显示网站图标（若获取失败则显示名称首字母作为占位）。</li></ul>",
                "<h4>隐藏弹窗与禁止提示</h4>",
                "<ul><li>隐藏弹窗：开启后，版本更新等通知弹窗将不再自动弹出，适合已熟悉更新内容的用户。</li><li>禁止提示：开启后，首次进入页面时关于新功能的提示弹窗将不再显示。</li></ul>",
                "<h3>快捷键</h3>",
                "<p>在设置页面开启「快捷键」后，可使用以下快捷键操作：</p>",
                "<table><tr><td>快捷键</td><td>功能</td></tr><tr><td>--------</td><td>------</td></tr><tr><td><code>Tab</code></td><td>快速聚焦到搜索框</td></tr><tr><td><code>Ctrl + ,</code></td><td>打开设置页面</td></tr><tr><td><code>Ctrl + H</code></td><td>展开 / 收起搜索历史框</td></tr><tr><td><code>Ctrl + S</code>（设置页面内）</td><td>应用当前设置</td></tr></table>",
                "<h3>手柄控制器</h3>",
                "<p>OOOInterface 支持游戏手柄操作，方便用户在连接手柄后进行浏览操作。</p>",
                "<ul><li>在设置页面勾选「手柄控制器」开关即可启用，连接手柄后屏幕中央会出现跟随光标。</li><li>启用后可配置左摇杆按下和右摇杆按下时的对应操作（如打开设置、刷新页面、切换搜索历史、切换壁纸常显示等）。</li><li>部分手柄还可在设置中调整光标速度及反转 A/B 键的映射关系。</li></ul>",
                "<h5>环形快捷菜单</h5>",
                "<p>按住 LB 键或单击 X 键可呼出环形快捷菜单（Radial Menu），松开右摇杆或方向键确认所选操作，按 B 键或 ESC 键退出。菜单包含以下八项操作：清空搜索框、粘贴剪贴板内容、打开设置、打开关于页面、切换搜索引擎、切换壁纸模式、刷新页面、复制搜索框内容。</p>",
                "<table><tr><td>按键</td><td>功能</td></tr><tr><td>------</td><td>------</td></tr><tr><td>左摇杆</td><td>控制光标移动</td></tr><tr><td>右摇杆 / 方向键</td><td>导航跳转，聚焦下一可交互元素</td></tr><tr><td>LT（左扳机）</td><td>清空搜索框内容；在搜索历史条目上聚焦时删除该条目</td></tr><tr><td>RT（右扳机）</td><td>将剪贴板内容粘贴至搜索框</td></tr><tr><td>A</td><td>确认 / 点击当前光标所指向的元素；长按底部铭牌可打开设置页面</td></tr><tr><td>B</td><td>返回 / 取消（关闭弹窗、收起侧边栏、退出快捷菜单等）</td></tr><tr><td>X</td><td>呼出环形快捷菜单，松手确认选择；菜单包含：清空、粘贴、设置、关于、搜索切换、壁纸模式、刷新、复制</td></tr><tr><td>Y</td><td>执行确认（等同 Enter）；在搜索框时触发搜索，在设置页时执行应用操作</td></tr><tr><td>LB</td><td>在滑块调节界面时减少数值；长按呼出环形快捷菜单</td></tr><tr><td>RB</td><td>在滑块调节界面时增加数值</td></tr><tr><td>左摇杆按下</td><td>可自定义操作（打开设置 / 刷新页面 / 切换搜索历史 / 切换壁纸常显示）</td></tr><tr><td>右摇杆按下</td><td>可自定义操作（同上）</td></tr></table>",
                "<h3>开发者模式</h3>",
                "<p>开发者模式暴露了更多调试与高级设置项，供进阶用户使用。</p>",
                "<p>可用功能包括：</p>",
                "<ul><li>字体大小调节：通过滑块或数值输入框调整全局字体缩放比例（0.5x ~ 2.0x）。</li><li>字体粗细调节：调整文字字重（100 ~ 900），自动四舍五入至 100 的整数倍。</li><li>搜索框厚度调节：调整搜索框的高度（0 ~ 600px）。</li><li>代理端口配置：选择或自定义本地代理端口，支持 8899（本地转发）、7890（Clash 默认）、8080 及 10809（V2Ray）等常用端口，也支持手动输入其他端口号。</li><li>修改完成后，点击「应用」保存更改，或点击「重置开发者模式」恢复出厂值。</li></ul>",
                "<h2>辅助页面</h2>",
                "<h3>关于页面</h3>",
                "<p>关于页面展示了当前版本的核心信息、版本号及历史版本记录。</p>",
                "<ul><li>打开方式：在设置页面点击右上角的「关于」按钮，或在主页面右键菜单中点击「关于」。</li><li>更新日志：在设置页面右上角的「关于」按钮上右键单击，可打开更新日志页面，查看详细的版本变更内容。</li></ul>",
                "<h3>反馈页面</h3>",
                "<p>反馈页面为用户提供了向开发者提交意见与建议的渠道。</p>",
                "<ul><li>打开方式：在设置页面点击右上角的「反馈」按钮，或在主页面右键菜单中点击「反馈」。</li><li>开发者模式下反馈按钮始终可见；非开发者模式下反馈按钮默认隐藏。</li></ul>"
            ]
        },
        {
            "id": 3,
            "label": "轻松升级",
            "title": "OOOInterface 轻松升级指南",
            "content": [
                "<blockquote>本指南介绍两种升级 OOOInterface 的方式：<strong>官网下载解压</strong> 和 <strong>OOOInterface 易升（OUA）</strong>。推荐优先使用 OUA，体验更省心。</blockquote>",
                "<h2>方式一：从官网下载解压</h2>",
                "<p>适合希望手动控制、或网络环境受限无法使用 OUA 的用户。</p>",
                "<h3>步骤</h3>",
                "<ol><li>打开 <a href=\"https://rudan177.github.io/OOOInterface/index.html\">OOOInterface 官网</a>，选择版本卡片进入下载页面。</li><li>下载对应操作系统的最新压缩包（<code>.zip</code>）。</li><li>关闭 OOOInterface 所有标签页（否则文件可能正在被占用）。</li><li>将下载的压缩包<strong>解压覆盖</strong>至 OOOInterface 安装目录（保留原有配置文件，主要覆盖 <code>index.html</code>、<code>css/</code>、<code>js/</code> 等核心文件即可）。</li><li>回到 <code>chrome://extensions/</code> 页面，点击 OOOInterface 卡片上的 <strong>刷新</strong> 按钮。</li><li>新建一个标签页，确认版本已更新。</li></ol>",
                "<blockquote><strong>提示</strong>：若不想覆盖全部文件，也可以直接下载完整的 ZIP，将整个解压后的文件夹重命名后替换原来的扩展目录。</blockquote>",
                "<h2>方式二：使用 OOOInterface 易升（OUA）</h2>",
                "<blockquote><strong>OOOInterface Update Assistant</strong>（简称 OUA）是配套 OOOInterface 的桌面工具，可自动检测新版本、一键更新、管理安装目录，并支持开机自启、最小化到托盘等习惯设置。</blockquote>",
                "<h3>获取 OOOInterface 易升</h3>",
                "<blockquote>从 <a href=\"https://rudan177.github.io/OOOInterface/OUA/PB\">OOOInterface 易升下载站</a> 下载 OOOInterface 易升。</blockquote>",
                "<h3>界面概览</h3>",
                "<p>OUA 启动后呈现三栏式布局，分为<strong>左 - 中-右</strong>三个区域：</p>",
                "<table><tr><td>区域</td><td>名称</td><td>说明</td></tr><tr><td>------</td><td>------</td><td>------</td></tr><tr><td>左侧大卡片</td><td><strong>更新面板</strong></td><td>显示安装目录、当前版本、远程版本、更新通道，并提供检查与更新操作</td></tr><tr><td>右上卡片</td><td><strong>通知面板</strong></td><td>展示官方推送的重要通知（如重大版本更新、维护公告等）</td></tr><tr><td>右下卡片</td><td><strong>关于本软件</strong></td><td>显示 OUA 自身版本号、操作系统类型，并提供检查更新的入口</td></tr></table>",
                "<h3>首次安装（零配置启动）</h3>",
                "<p>OUA 首次运行时，若未检测到有效安装目录，会引导你完成初始化：</p>",
                "<ol><li>启动 OUA，界面中央显示「未设置」的安装目录。</li><li>点击 <strong>「更换」</strong> 按钮，弹出系统文件夹选择对话框，选择 OOOInterface 的安装目录（即 <code>chrome://extensions/</code> 中 OOOInterface 的路径）。</li><li>OUA 会自动检测目录状态，并给出对应引导：</li></ol>",
                "<ul><li><strong>空目录</strong> → 弹出三选项对话框：</li><li><strong>从远程拉取</strong>：默认使用 LTS 通道，自动从 GitHub 克隆最新代码到目标目录。</li><li><strong>从本地导入</strong>：弹出文件选择框，让你导入已有的 ZIP 压缩包。</li><li><strong>取消</strong>：退出流程。</li><li><strong>完整目录</strong> → 直接进入正常更新检测流程。</li></ul>",
                "<h3>日常更新</h3>",
                "<p>目录设置完成后，日常使用只需两步：</p>",
                "<ol><li><strong>检查更新</strong>：点击主按钮「检查更新」，OUA 会自动读取本地版本并与 GitHub 远程分支比对。</li><li><strong>执行更新</strong>：若发现新版本，按钮变为「立即更新」，点击后 OUA 会在后台静默下载并覆盖文件，完成后自动刷新界面。</li></ol>",
                "<blockquote>若本地版本高于远程正式版，OUA 会提示「当前版本高于正式版，是否加入尝鲜版？」，用户可选择切换到尝鲜版通道。</blockquote>",
                "<h3>更新通道（分支管理）</h3>",
                "<p>更新面板中的「更新通道」支持两种顶层模式，各有三个子选项：</p>",
                "<h4>远程模式</h4>",
                "<p>自动从 GitHub 获取更新，适用于网络通畅的环境。</p>",
                "<table><tr><td>子分支</td><td>说明</td></tr><tr><td>--------</td><td>------</td></tr><tr><td><strong>长期支持版（LTS）</strong></td><td>稳定优先，适合日常使用，更新频率较低</td></tr><tr><td><strong>正式版（main）</strong></td><td>跟随主干开发，功能较新，稳定性与 LTS 相当</td></tr><tr><td><strong>尝鲜版（test）</strong></td><td>包含最新实验性功能，更新最频繁，可能存在不稳定因素</td></tr></table>",
                "<p>切换分支时，OUA 会智能比对当前版本与各分支的远程版本，自动推荐最合适的目标分支；若智能判断失败，也会弹出三按钮手动选择。</p>",
                "<h4>本地模式</h4>",
                "<p>跳过网络检测，直接通过 ZIP 压缩包导入更新。适合：</p>",
                "<ul><li>断网或网络受限环境</li><li>测试人员分发自定义版本</li><li>内网部署场景</li></ul>",
                "<p>切换到本地模式后，主按钮变为「导入」，点击后弹出文件选择框；也可以直接将 ZIP 文件<strong>拖拽到 OUA 窗口</strong>，松开后自动完成导入解压。</p>",
                "<h3>设置面板</h3>",
                "<p>点击更新面板中的 <strong>齿轮图标</strong>，可展开顶部开关区；齿轮图标右侧还有一个<strong>独立的完整设置弹窗</strong>，包含以下三类设置：</p>",
                "<h4>1. 启动与托盘</h4>",
                "<table><tr><td>开关</td><td>功能</td></tr><tr><td>------</td><td>------</td></tr><tr><td><strong>开机启动</strong></td><td>系统启动时自动运行 OUA，无需手动打开</td></tr><tr><td><strong>最小化到托盘</strong></td><td>关闭窗口时隐藏至系统托盘（任务栏旁小图标），不退出程序，双击托盘图标或热键可重新唤出窗口</td></tr></table>",
                "<blockquote>开启「最小化到托盘」是<strong>热键功能的前置条件</strong>，未开启时 ESC 快捷键不生效。</blockquote>",
                "<h4>2. 自动更新</h4>",
                "<table><tr><td>开关</td><td>功能</td></tr><tr><td>------</td><td>------</td></tr><tr><td><strong>自动更新</strong></td><td>检测到新版本时自动下载，完成后等待用户手动确认安装</td></tr></table>",
                "<h4>3. 热键（需在「最小化到托盘」开启时显示）</h4>",
                "<table><tr><td>项目</td><td>说明</td></tr><tr><td>------</td><td>------</td></tr><tr><td><strong>热键开关</strong></td><td>启用全局快捷键</td></tr><tr><td><strong>打开窗口</strong></td><td>默认 <code>Ctrl+Shift+O</code>，可点击「改」自定义——点击后键盘区域闪烁，此时按下任意组合键即设定为新热键；点击「↺」可重置为默认值</td></tr><tr><td><strong>ESC 关闭</strong></td><td>开启最小化到托盘后，按 <code>ESC</code> 可快速隐藏 OUA 窗口（仅当对话框/设置弹窗未打开时生效）</td></tr></table>",
                "<h4>4. 网络代理设置</h4>",
                "<p>解决 GitHub 访问受限问题（常见于国内网络环境）。</p>",
                "<ul><li><strong>自动配置代理</strong>：OUA 自动读取系统代理设置，适合大多数使用 Clash / V2Ray 等代理工具的用户。</li><li><strong>手动配置代理</strong>：勾选「启用代理」后展开 IP 和端口输入框，填入代理服务器地址（如 <code>127.0.0.1</code>）和端口号（如 <code>7890</code>、<code>10809</code>）。</li></ul>",
                "<p>代理修改后点击「应用」立即生效，无需重启。</p>",
                "<h4>5. 可访问性（供高级用户）</h4>",
                "<ul><li><strong>可访问开关</strong>：启用后可访问性 API，允许外部程序通过 HTTP 接口操控 OUA。</li><li><strong>端口</strong>：可访问服务监听的端口，默认 <code>8964</code>。</li><li><strong>OOOInterface 访问</strong>：允许 OOOInterface 通过本地接口与 OUA 通信（通常保持开启）。</li><li><strong>外部访问开关</strong>：允许局域网内其他设备通过令牌访问 OUA 服务。</li><li><strong>访问令牌</strong>：用于身份验证的 Token，可点击「编辑」按钮修改、点击「复制」按钮复制、点击「重新生成」按钮更换。</li><li><strong>状态指示条</strong>：实时显示服务器运行状态（绿色圆点 = 运行中，灰色 = 未运行）。</li></ul>",
                "<h4>6. 系统操作</h4>",
                "<table><tr><td>按钮</td><td>功能</td></tr><tr><td>------</td><td>------</td></tr><tr><td><strong>关闭并重启</strong></td><td>保存当前设置并重启 OUA，使设置立即生效</td></tr><tr><td><strong>恢复出厂设置</strong></td><td>清除所有用户配置（代理、热键、启动项等），操作不可撤销，需二次确认</td></tr></table>",
                "<h3>通知与关于面板</h3>",
                "<h4>通知面板</h4>",
                "<ul><li>自动从云端拉取官方通知，展示重要公告（如重大版本变更、维护提醒）。</li><li>每次打开 OUA 时自动刷新，无需手动操作。</li><li>通知内容点击可跳转至对应详情页面。</li></ul>",
                "<h4>关于本软件面板</h4>",
                "<ul><li>显示 OUA 的短版本号（如 <code>0.9.3</code>）和完整版本号（如 <code>0.9.3-BS112</code>）。</li><li><strong>单击版本号</strong>可展开详细信息，包括完整版本、操作系统、当前更新状态。</li><li>版本号旁的<strong>圆点</strong>表示有可用更新，点击「检查更新」按钮可触发 OUA 自身的更新流程（下载新版本安装包，点击「更新」后打开安装包完成覆盖安装）。</li><li>底部显示联系方式 <code>wyjcrtu@proton.me</code> 和版权声明。</li></ul>",
                "<h3>拖放导入（本地模式特有）</h3>",
                "<p>在本地模式下，OUA 支持<strong>拖放文件</strong>功能：</p>",
                "<ol><li>将更新通道切换至「本地」。</li><li>用鼠标将 <code>.zip</code> 压缩包拖入 OUA 窗口。</li><li>窗口会出现半透明遮罩提示「释放 ZIP 文件以导入」。</li><li>松开鼠标，OUA 自动完成解压覆盖，无需额外点击。</li></ol>",
                "<blockquote>此功能同样支持在远程模式下拖放，拖放后会自动切换到本地模式再导入。</blockquote>",
                "<h3>卸载</h3>",
                "<p>OUA 提供内置卸载功能：</p>",
                "<ol><li>点击更新面板底部的<strong>垃圾桶图标</strong>（一键卸载）。</li><li>按卸载向导提示操作，将清理 OUA 自身文件及注册表项。</li><li>卸载完成后 OOA 自动退出。</li></ol>",
                "<blockquote>卸载 OUA <strong>不会影响</strong>已安装的 OOOInterface 扩展本身，如需同时移除扩展，请自行在 <code>chrome://extensions/</code> 中操作。</blockquote>",
                "<h2>两种方式对比</h2>",
                "<table><tr><td>特性</td><td>官网下载解压</td><td>OUA 易升</td></tr><tr><td>------</td><td>-------------</td><td>---------</td></tr><tr><td>操作难度</td><td>中等，需手动找目录</td><td>低，图形化引导全程</td></tr><tr><td>自动化程度</td><td>无，全手动</td><td>自动检测 → 自动下载 → 自动覆盖</td></tr><tr><td>网络要求</td><td>需手动下载压缩包</td><td>远程模式需联网，支持代理配置</td></tr><tr><td>分支管理</td><td>需手动选择下载对应版本</td><td>一键切换 LTS / main / test</td></tr><tr><td>拖放导入</td><td>不支持</td><td>支持本地 ZIP 拖放</td></tr><tr><td>热键唤起</td><td>不支持</td><td>支持自定义热键（默认 Ctrl+Shift+O）</td></tr><tr><td>开机自启</td><td>不支持</td><td>支持</td></tr><tr><td>托盘后台运行</td><td>不支持</td><td>支持</td></tr><tr><td>自动更新</td><td>不支持</td><td>支持</td></tr><tr><td>代理配置</td><td>需手动设置系统代理</td><td>OUA 内置代理设置，即时生效</td></tr><tr><td>通知推送</td><td>无</td><td>自动拉取官方通知</td></tr></table>",
                "<h2>常见问题</h2>",
                "<p><strong>Q：OUA 提示\"无法获取远程版本，请检查网络\"？</strong></p>",
                "<p>A：可能是网络环境问题。可在 OUA 设置 → 网络代理设置中开启代理，或使用自动配置模式；也可临时切换到本地模式导入 ZIP 压缩包。</p>",
                "<p><strong>Q：更新后 OOOInterface 没有生效？</strong></p>",
                "<p>A：请回到 <code>chrome://extensions/</code> 页面点击 OOOInterface 的「刷新」按钮，然后新建标签页确认版本已更新。若仍未生效，可尝试禁用再重新启用该扩展。</p>",
                "<p><strong>Q：OUA 窗口关掉了怎么重新打开？</strong></p>",
                "<p>A：</p>",
                "<ul><li>若开启了「最小化到托盘」，双击托盘图标或按默认热键 <code>Ctrl+Shift+O</code> 唤出。</li><li>若未开启托盘，可在开始菜单搜索 \"OOOInterface Update Assistant\" 或 \"易升\" 启动。</li></ul>",
                "<p><strong>Q：OUA 会自动更新 OOOInterface 吗？</strong></p>",
                "<p>A：在「自动更新」开关开启且处于远程模式时，OUA 检测到新版本会自动下载，但不会自动安装，仍需点击「立即更新」确认。</p>",
                "<p><strong>Q：OUA 和 OOOInterface 是什么关系？</strong></p>",
                "<p>A：OUA 是 OOOInterface 的配套桌面工具，负责更新管理，本身不是浏览器扩展。两者由同一团队开发，配合使用体验最佳。</p>",
                "<p><strong>Q：可以同时使用两种方式吗？</strong></p>",
                "<p>A：可以。两种方式互不影响，选择最适合你当前场景的方式即可。</p>",
                "<p><strong>Q：OUA 会收集我的数据吗？</strong></p>",
                "<p>A：OUA 仅在更新检测时访问 GitHub API，所有操作均在本地完成，不上传任何个人信息或扩展数据。</p>",
                "<blockquote>如有问题，欢迎通过 OUA 内置反馈页面或邮件联系开发者：<a href=\"mailto:wyjcrtu@proton.me\">wyjcrtu@proton.me</a> © 2026 ByRUDAN 保留所有权利。</blockquote>"
            ]
        }
    ]
};
