var DOC_DATA = {
    "meta": {
        "docNumber": "BRD-OOO-260723.THEME",
        "version": "v1.1:02",
        "date": "2026-07-23",
        "status": "现行有效",
        "pageTitle": "主题文档编写规范",
        "pageBrand": "OOOInterface",
        "pageTitleMain": "主题文档编写规范",
        "pageSubtitle": "OOOInterface 29 主题系统开发指南",
        "footerLeft": "OOOInterface",
        "footerRight": "ByRUDAN"
    },
    "sections": [
        {
            "id": 0,
            "label": "基本介绍",
            "title": "基本介绍",
            "content": [
                "<p>OOOInterface Themes 是 OOOInterface 29 推出的全新主题系统。Themes 允许用户自定义 OOOInterface 的外观。基础的，有 LOGO、字体、壁纸、主题色；此外，还支持高级内容自定义————开发者可以完全自定义 Style.css 中任何定义项的内容。</p>",
                "<p>OOOInterface 认为，仅仅由极少量开发者设计的主题无法满足所有用户的需求，因此 OOOInterface 决定开放主题系统，允许开发者设计自己的主题。后续，OOOInterface 还将不断完善主题开发者的开发体验，提供更加便捷的开发体验。</p>",
                "<div class='version-card'>",
                "<h3 class='version-subtitle'>适用人群</h3>",
                "<ul>",
                "<li>主题设计师</li>",
                "<li>前端开发者</li>",
                "<li>自定义主题爱好者</li>",
                "</ul>",
                "<h3 class='version-subtitle'>前置基础</h3>",
                "<ul>",
                "<li>基础 JSON 知识</li>",
                "<li>基础 JavaScript 知识</li>",
                "<li>基础 CSS 知识（非必要）</li>",
                "</ul>",
                "<h3 class='version-subtitle'>适配版本</h3>",
                "<p>OOOInterface 29.0 或更高版本</p>",
                "</div>"
            ]
        },
        {
            "id": 1,
            "label": "官方资源",
            "title": "官方资源",
            "content": [
                "<p>OOOInterface 为主题主题设计师提供丰富的官方资源。</p>",
                "<h3>Logo 资源</h3>",
                "<ul>",
                "<li><strong>林绿色（默认）</strong></li>",
                "</ul>",
                "<pre data-lang='url'><code>https://rudan177.github.io/OOOInterface/images/dll.png</code></pre>",
                "<ul>",
                "<li><strong>黑白色</strong></li>",
                "</ul>",
                "<pre data-lang='url'><code>https://rudan177.github.io/OOOInterface/images/logo/blk.png</code></pre>",
                "<ul>",
                "<li><strong>天依蓝</strong></li>",
                "</ul>",
                "<pre data-lang='url'><code>https://rudan177.github.io/OOOInterface/images/logo/tyb.png</code></pre>",
                "<ul>",
                "<li><strong>活力红</strong></li>",
                "</ul>",
                "<pre data-lang='url'><code>https://rudan177.github.io/OOOInterface/images/logo/red.png</code></pre>",
                "<ul>",
                "<li><strong>典藏金</strong></li>",
                "</ul>",
                "<pre data-lang='url'><code>https://rudan177.github.io/OOOInterface/images/logo/gld.png</code></pre>",
                "<ul>",
                "<li><strong>爱上雷神</strong></li>",
                "</ul>",
                "<pre data-lang='url'><code>https://rudan177.github.io/OOOInterface/images/logo/iso.png</code></pre>",
                "<h3>壁纸资源</h3>",
                "<ul>",
                "<li><strong>原神丝柯克壁纸（默认）</strong></li>",
                "</ul>",
                "<pre data-lang='url'><code>https://rudan177.github.io/OOOInterface/images/back.png</code></pre>",
                "<ul>",
                "<li><strong>人民的CEO壁纸（经典）</strong></li>",
                "</ul>",
                "<pre data-lang='url'><code>https://rudan177.github.io/OOOInterface/images/wallpaper/classic.png</code></pre>",
                "<ul>",
                "<li><strong>无尽蓝专辑封面</strong></li>",
                "</ul>",
                "<pre data-lang='url'><code>https://rudan177.github.io/OOOInterface/images/wallpaper/tyb.jpg</code></pre>",
                "<p>OOOInterface 将持续为主题设计师提供丰富多彩的官方设计资源。</p>"
            ]
        },
        {
            "id": 2,
            "label": "原理概述",
            "title": "原理概述",
            "content": [
                "<p>OOOInterface Themes 基于 JSON 配置文件，但为保证添加主题的稳定体验，将以 JavaScript 格式保存。将 Themes 导入 OOOInterface 有两种方案：</p>",
                "<ul>",
                "<li><strong>开发者方案</strong>：将完成编译的主题文件添加至 OOOInterface 的 Themes 目录下，遂手动编辑 themes.json 。该方案有利于主题长期存在而不受浏览器更换影响。该方案仅支持 JavaScript 格式。</li>",
                "<li><strong>标准方案</strong>：将编译完成的主题文件添加/拖入 OOOInterface 设置页主题选择面板。该方案支持 JavaScript 和 JSON 双格式。</li>",
                "</ul>",
                "<p>Themes 的核心加载逻辑在 script.js 中。<code>applyTheme(themeKey)</code> 是主题应用的核心函数。其读取主题文件中元数据并将其应用到 OOOInterface 中。</p>",
                "<p>除了基本的主题应用，为保证 Themes 能够逻辑通畅，内还包含以下逻辑：</p>",
                "<ol>",
                "<li><p><code>this.themeOverrides</code> 对象用于存储当前主题对 logo / font / wallpaper 的专用配置，与用户普通设置区分开，确保主题切换时能正确应用和清理。</p></li>",
                "<li><p><code>checkThemeConsistency()</code>：</p>",
                "<ul>",
                "<li>当用户手动修改了字体、Logo、壁纸或配色中的任一项，如果新值与当前主题定义的不一致， 自动关闭主题功能</li>",
                "<li>这避免了\"主题已启用但实际显示是自定义混搭\"的不一致状态</li>",
                "</ul>",
                "</li>",
                "<li><p><code>handleThemeUpload()</code> 支持用户导入自定义主题文件，兼容 JSON 和 JS 两种格式，导入后存入 settings.customThemes 持久化保存。</p></li>",
                "</ol>"
            ]
        },
        {
            "id": 3,
            "label": "文件结构",
            "title": "文件结构",
            "content": [
                "<p>主题文件的基本结构如下：</p>",
                "<pre data-lang='JSON'><code>{\n    \"info\": {                 // 主题元信息\n        \"name\": \"\",           // 主题名称\n        \"designer\": \"\",       // 设计师\n        \"version\": \"\"         // 版本号\n    },\n    \"details\": {              // 主题具体配置\n        \"logo\": { ... },      // Logo 配置\n        \"font\": { ... },      // 字体配置\n        \"wallpaper\": { ... }, // 壁纸配置\n        \"color\": { ... },     // 配色方案\n        \"more\": false         // 是否有额外自定义 CSS\n    }\n}</code></pre>",
                "<p>接下来将详细介绍各字段的详细内容。</p>"
            ]
        },
        {
            "id": 4,
            "label": "主题元信息",
            "title": "主题元信息",
            "content": [
                "<p>主题原信息皆为字符串，因此可以畅所欲言。但如若您希望未来您的主题能够收录入 OOOInterface 主题库，您需要遵守以下规范：</p>",
                "<ul>",
                "<li><strong>name、designer</strong>：10字符以内，不限制语言，禁止使用非文本字符，尤其禁止使用emoji表情。</li>",
                "<li><strong>version</strong>：请严格按照 BRD 版本号规范。",
                "<ul>",
                "<li>BRD 版本号规范：<code>x.y(.z):a</code>。</li>",
                "<li>x：主版本号，y：次版本号，z：修订版本号（可选），a：发布次号（&gt;10时十位填0）。</li>",
                "<li>例：<code>1.0:01</code>，<code>1.0.1:02</code>，<code>2.0:03</code>。</li>",
                "</ul>",
                "</li>",
                "</ul>"
            ]
        },
        {
            "id": 5,
            "label": "Logo 配置",
            "title": "Logo 配置",
            "content": [
                "<pre data-lang='JSON'><code>\"logo\": {\n    \"name\": \"\",             // Logo 名称\n    \"location\": \"\",         // Logo 本地相对路径\n    \"specialStyle\": {       // 其他定义（选填）\n        \"dark\": \"\",         // 暗色 Logo 本地相对路径\n        \"online\": \"\",       // 在线 Logo 云端路径\n        \"onlineDark\": \"\",   // 在线 Logo 暗色 Logo 云端路径\n        \"width\": \"\",        // Logo 宽度（如不填则等同于高度，两者都不填默认120px）\n        \"height\": \"\"        // Logo 高度（如不填则等同于宽度）\n    }\n},</code></pre>",
                "<p><strong>注：</strong></p>",
                "<ol>",
                "<li>LOGO 会先加载本地 LOGO，随后检测云端连通性，并在云端 LOGO 加载完毕后显示云端 LOGO。</li>",
                "<li><code>location</code> 允许直接填写云端路径，无需本地相对路径。但如果同时存在本地和云端 LOGO，则<code>location</code>必须填写本地相对路径，云端链接填写在<code>specialStyle</code>中<code>online</code>。</li>",
                "<li>若存在<code>dark</code>，但不存在<code>onlineDark</code>，则暗色模式使用<code>dark</code>。</li>",
                "</ol>"
            ]
        },
        {
            "id": 6,
            "label": "字体配置",
            "title": "字体配置",
            "content": [
                "<pre data-lang='JSON'><code>\"font\": {\n    \"name\": \"\",             // 字体名称\n    \"location\": \"\",         // 字体本地相对路径\n    \"specialStyle\": {       // 其他定义（选填）\n        \"font-weight\": \"\",    // 字体粗细\n        \"font-size\": \"\"        // 字体大小\n    }\n},</code></pre>",
                "<p><strong>注：</strong></p>",
                "<ol>",
                "<li>字体粗细留空默认400。</li>",
                "<li>字体大小单位为em，即倍数。留空默认1em。</li>",
                "<li>字体暂不提供<code>online</code>。</li>",
                "</ol>"
            ]
        },
                {
            "id": 7,
            "label": "壁纸配置",
            "title": "壁纸配置",
            "content": [
                "<pre data-lang='JSON'><code>\"wallpaper\": {\n    \"name\": \"\",             // 壁纸名称\n    \"location\": \"\",         // 壁纸本地相对路径\n    \"specialStyle\": {       // 其他定义（选填）\n        \"online\": \"\",       // 在线壁纸云端路径\n        \"wallpaperFill\":    // 是否填充壁纸（true/false）\n    }\n},</code></pre>",
                "<p><strong>注：</strong></p>",
                "<ol>",
                "<li><code>wallpaperFill</code> 对应设置页壁纸面板\"填满\"开关，请填写true（开）false（关）。留空则遵循用户设定。建议打开（不想被用户骂的话）。</li>",
                "</ol>"
            ]
        },
        {
            "id": 8,
            "label": "配色方案",
            "title": "配色方案",
            "content": [
                "<pre data-lang='JSON'><code>\"color\": {\n    \"name\": \"\",             // 配色方案名称\n    \"specialStyle\": {       // 其他定义（选填）\n        \"colorGroup\": \"\",     // 配色方案组（cjs、add）\n        \"colorScheme\": \"\"     // 配色方案\n    }\n},</code></pre>",

                "<h4 style='margin: 14px 0 8px; font-size: 0.92rem; font-weight: 600; color: var(--text-heading);'><code>colorGroup</code>和<code>colorScheme</code></h4>",
                "<p><strong>1. 引用内置配色<code>colorGroup</code>: \"cjs\"</strong> ：直接引用系统内置的配色方案：</p>",
                "<ul>",
                "<li><code>colorGroup</code>: \"cjs\" — 表示使用 color.js 中预定义的配色方案</li>",
                "<li><code>colorScheme</code> — 配色方案的 key，从内置方案中选一个</li>",
                "</ul>",
                "<p style='margin-left: 24px;'>内置方案都定义在 color.js 的 <code>COLOR_SCHEME_CONFIGS</code> 中：</p>",
                "<table>",
                "<thead>",
                "<tr>",
                "<th>colorScheme 值</th>",
                "<th>名称</th>",
                "<th>主色</th>",
                "</tr>",
                "</thead>",
                "<tbody>",
                "<tr><td><code>green</code></td><td>林绿色</td><td><code>#00AE90</code></td></tr>",
                "<tr><td><code>blue</code></td><td>经典蓝</td><td><code>#1a73e8</code></td></tr>",
                "<tr><td><code>black-white</code></td><td>黑白色</td><td><code>#000000</code></td></tr>",
                "<tr><td><code>tianyi-blue</code></td><td>天依蓝</td><td><code>#66ccff</code></td></tr>",
                "<tr><td><code>vibrant-red</code></td><td>活力红</td><td><code>#FF0000</code></td></tr>",
                "<tr><td><code>classic-gold</code></td><td>典藏金</td><td><code>#B46300</code></td></tr>",
                "<tr><td><code>isolation</code></td><td>隔离色</td><td><code>#FFD700</code></td></tr>",
                "<tr><td><code>custom</code></td><td>自定义</td><td>—</td></tr>",
                "</tbody>",
                "</table>",

                "<p><strong>2. 主题自带完整配色<code>colorGroup</code>: \"add\"</strong> ：自带一套完整的配色配置，不依赖内置方案：</p>",
                "<ul>",
                "<li><code>colorGroup</code>: \"add\" — 表示主题自带完整配色</li>",
                "<li><code>colorScheme</code> — 直接放完整的配色配置对象（字段见下方说明）</li>",
                "</ul>",
                "<p style='margin-left: 24px;'>如果使用 <code>colorGroup: \"add\"</code> ， <code>colorScheme</code> 对象中可以包含以下字段：</p>",
                "<table>",
                "<thead>",
                "<tr>",
                "<th>字段</th>",
                "<th>类型</th>",
                "<th>说明</th>",
                "</tr>",
                "</thead>",
                "<tbody>",
                "<tr><td><code>accent</code></td><td>string</td><td>主色（亮色模式）</td></tr>",
                "<tr><td><code>accentRgb</code></td><td>string</td><td>主色 RGB 格式（如 \"255, 102, 0\" ），用于 rgba 透明度</td></tr>",
                "<tr><td><code>accentDark</code></td><td>string</td><td>主色（暗色模式）</td></tr>",
                "<tr><td><code>accentDarkRgb</code></td><td>string</td><td>暗色模式主色 RGB</td></tr>",
                "<tr><td><code>accentHover</code></td><td>string</td><td>悬停态颜色</td></tr>",
                "<tr><td><code>accentActive</code></td><td>string</td><td>激活/按下态颜色</td></tr>",
                "<tr><td><code>gradient</code></td><td>string</td><td>可选，渐变色（亮色），如 linear-gradient(135deg, #xxx, #yyy)</td></tr>",
                "<tr><td><code>gradientDark</code></td><td>string</td><td>可选，渐变色（暗色）</td></tr>",
                "<tr><td><code>contextMenuHover</code></td><td>string</td><td>右键菜单悬停背景色</td></tr>",
                "<tr><td><code>contextMenuHoverDark</code></td><td>string</td><td>暗色模式右键菜单悬停背景色</td></tr>",
                "<tr><td><code>contextMenuTextColor</code></td><td>string</td><td>右键菜单文字色</td></tr>",
                "<tr><td><code>contextMenuTextColorDark</code></td><td>string</td><td>暗色模式右键菜单文字色</td></tr>",
                "<tr><td><code>sidebarIcon</code></td><td>string</td><td>侧边栏图标颜色</td></tr>",
                "<tr><td><code>notificationBg</code></td><td>string</td><td>通知背景色（带透明度）</td></tr>",
                "<tr><td><code>notificationBgDark</code></td><td>string</td><td>暗色模式通知背景色</td></tr>",
                "<tr><td><code>notificationText</code></td><td>string</td><td>通知文字颜色</td></tr>",
                "<tr><td><code>notificationBorder</code></td><td>string</td><td>通知边框颜色</td></tr>",
                "<tr><td><code>infoClass</code></td><td>string</td><td>信息面板样式类名</td></tr>",
                "<tr><td><code>particleHueMin</code></td><td>number</td><td>粒子效果最小色相（0-360）</td></tr>",
                "<tr><td><code>particleHueRange</code></td><td>number</td><td>粒子色相范围</td></tr>",
                "<tr><td><code>particleSaturation</code></td><td>number</td><td>粒子饱和度（0-100）</td></tr>",
                "<tr><td><code>glowOrbs</code></td><td>string[]</td><td>光晕球颜色数组（4 个，带透明度）</td></tr>",
                "</tbody>",
                "</table>"
            ]
        },
        {
            "id": 9,
            "label": "额外CSS",
            "title": "额外CSS",
            "content": [
                "<pre data-lang='JSON'><code>\"more\": ,            // 额外CSS（true/false）\n\"moreStyle\"{}        // 额外CSS样式（当more为true时）</code></pre>",
                "<p><strong>注：</strong></p>",
                "<ol>",
                "<li>在使用<code>moreStyle</code>自定义 CSS 时，请确保您有必要的 CSS 知识，且已熟悉 OOOInterface CSS内容和规范。</li>",
                "<li><code>moreStyle</code> 中的 CSS 代码关联 style.css ，因此无法影响高级视觉效果。</li>",
                "<li><code>moreStyle</code> 编写实例：",
                "<ol style='margin-top: 8px;'>",
                "<li>注意到 style.css 中",
                "<pre data-lang='CSS'><code>.search-container {\n    position: relative;\n    z-index: 1;\n    display: flex;\n    align-items: center;\n    border: 1px solid var(--border-color);\n    border-radius: var(--border-radius);            /* 圆角 */\n    background: #F1F3F4;\n    transition: border-color 0.2s ease,\n                box-shadow 0.2s ease,\n                background 0.3s cubic-bezier(0.4, 0, 0.2, 1),\n                backdrop-filter 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n    padding: 0 16px;\n    height: 48px;\n    width: 100%;\n    max-width: 560px;\n    margin: 0 auto;\n    box-sizing: border-box;\n}</code></pre>",
                "</li>",
                "<li>那么我们便可 <code>moreStyle</code> 中添加自定义 CSS 代码将圆角更改为定值 <code>50px</code> 。",
                "<pre data-lang='JSON'><code>\"moreStyle\": {\n    \"specialStyle\": {\n        \".search-container\": \"border-radius: 50px !important;\"\n    }\n}</code></pre>",
                "</li>",
                "</ol>",
                "</li>",
                "</ol>"
            ]
        },
        {
            "id": 10,
            "label": "测试方式",
            "title": "测试方式",
            "content": [
                "<p> OOOInterface 29 测试版现已发布，您可以在测试版中测试您的主题。</p>",
                "<p>为确保稳定，建议：</p>",
                "<ol>",
                "<li>测试时使用\"开发者方案\"导入，随后通过多次重置验证效果。</li>",
                "<li>若无法确保自己精通CSS，请不要乱改 <code>more</code> 在 OOOInterface 的 CSS 上拉屎，这会影响您自身使用体验。</li>",
                "<li>自己写配色，请一定要检查深浅色、高级视觉效果下的显示效果。若发现有逻辑错误，请第一时间联系 wyjcrtu@proton.me。</li>",
                "</ol>",
                "<hr>",
                "<p style='text-align: center; font-size: 0.95rem; color: var(--text-muted); font-style: italic;'>为更棒的 OOOInterface 预备好！</p>"
            ]
        }
    ]
};
